# CRUD Workflow
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: echo-demo-task-
  namespace: argo
spec:
  entrypoint: main
  serviceAccountName: argo

  templates:
  - name: main
    steps:
      - - name: run-create
          template: create
      - - name: run-read
          template: read
      - - name: run-update
          template: update
      - - name: run-delete
          template: delete

  - name: create
    container:
      image: amazon/aws-cli:latest
      env:
        - name: AWS_ACCESS_KEY_ID
          value: "minioadmin"
        - name: AWS_SECRET_ACCESS_KEY
          value: "thisisfortesting"
      command: ["sh", "-c"]
      args:
        - |
          FILE="/tmp/himinio.txt"
          BUCKET="testbucket"
          ENDPOINT="http://minio:9000"

          # Build bucket
          aws --endpoint-url $ENDPOINT s3 mb s3://$BUCKET || true

          echo "create success" >> $FILE
          aws --endpoint-url $ENDPOINT s3 cp $FILE s3://$BUCKET/himinio.txt
          cat $FILE

  - name: read
    container:
      image: amazon/aws-cli:latest
      env:
        - name: AWS_ACCESS_KEY_ID
          value: "minioadmin"
        - name: AWS_SECRET_ACCESS_KEY
          value: "thisisfortesting"
      command: ["sh", "-c"]
      args:
        - |
          FILE="/tmp/himinio.txt"
          BUCKET="testbucket"
          ENDPOINT="http://minio:9000"

          aws --endpoint-url $ENDPOINT s3 cp s3://$BUCKET/himinio.txt $FILE || touch $FILE
          echo "read success" >> $FILE
          aws --endpoint-url $ENDPOINT s3 cp $FILE s3://$BUCKET/himinio.txt
          cat $FILE

  - name: update
    container:
      image: amazon/aws-cli:latest
      env:
        - name: AWS_ACCESS_KEY_ID
          value: "minioadmin"
        - name: AWS_SECRET_ACCESS_KEY
          value: "thisisfortesting"
      command: ["sh", "-c"]
      args:
        - |
          FILE="/tmp/himinio.txt"
          BUCKET="testbucket"
          ENDPOINT="http://minio:9000"

          aws --endpoint-url $ENDPOINT s3 cp s3://$BUCKET/himinio.txt $FILE || touch $FILE
          echo "update success" >> $FILE
          aws --endpoint-url $ENDPOINT s3 cp $FILE s3://$BUCKET/himinio.txt
          cat $FILE

  - name: delete
    container:
      image: amazon/aws-cli:latest
      env:
        - name: AWS_ACCESS_KEY_ID
          value: "minioadmin"
        - name: AWS_SECRET_ACCESS_KEY
          value: "thisisfortesting"
      command: ["sh", "-c"]
      args:
        - |
          FILE="/tmp/himinio.txt"
          BUCKET="testbucket"
          ENDPOINT="http://minio:9000"

          aws --endpoint-url $ENDPOINT s3 cp s3://$BUCKET/himinio.txt $FILE || touch $FILE
          echo "delete success" >> $FILE
          aws --endpoint-url $ENDPOINT s3 cp $FILE s3://$BUCKET/himinio.txt
          cat $FILE
